### ISSUE TITLE
Is inertial value being considered?

### ISSUE THREAD

**Issue by daeunSong** [ridgeback/ridgeback_manipulation#2]
Hi, 

first of all, I would like to thank you for your work to integrate manipulators with Ridgeback. 

I am working on the integration with KUKA IIWA 7 R800 and Ridgeback.

This is more of a question than an issue. I wonder if inertial values are being considered completely. 
Since there are more than a robot model mounted on top of Ridgeback (i.e. table top, table legs, arm mount), I am guessing that all the inertial values for these are necessary for an accurate simulation. 

I could find inertial parameters from a ridgeback_description package and iiwa_description package for each robots, but could not find any parameters for extra models for mounting (i.e. table top, table legs, arm mount). 

I wonder if you have already done this job, or if you are in progress.

Thanks.

**Comment by david0429** [comment]
Inertia for the table and support has not been implemented, so a simulation with these components will not be completely accurate

**Comment by dniewinski** [comment]
Inertia for the table or supports are not taken into account so a simulation with these components will be inaccurate.  If you update the package with these changes, we would happily review them through a PR

**Comment by NithishkumarS** [comment]
Our setup has a Ridgeback and UR10e. I would be happy to make a PR with the inertia values for the hams table. Would it be possible to help me find the right mass/ other specifications for the individual components (table top, legs, arm mount)? cc: @dniewinski
