### ISSUE TITLE
question about the integration of ur5 and ridgeback

### ISSUE THREAD

**Issue by TouchDeeper** [ridgeback/ridgeback_manipulation#5]
Hi,
We buy the ridgeback and ur5 just now, but how can I integrate the hardware of these two robots, I can't find any document about the integration. Fortunately，I see the brilliant project video of ridgeback+ur in the web of Clearpath.  Can you provide some documentation about the integration of these two robot hardware?  Thanks a million!

**Comment by dniewinski** [comment]
Hi @TouchDeeper.  Sorry for the delay responding.  That integration is something usually done internally by our integrators here at Clearpath.  The parts and processes to do that aren't publicly available as most end up being custom for the application.  If you would like to have your arm integrated in this way, please contact Clearpath Sales and we can work out some options for you.
